[package]
name = "greeter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "0.15.6"
gio = "0.15.6"
lightdm-gobject-sys = { path = "../lightdm-gobject-sys" }
